In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
arr.ndim

1

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2.ndim

2

In [10]:
arr5 = np.array([1,2,3,4,5],ndmin=5)

In [11]:
arr5.ndim

5

In [12]:
arr5.dtype

dtype('int32')

In [13]:
arr5 = np.array([1,2,3,4,5],ndmin=5,dtype='int8')

In [14]:
arr5.dtype

dtype('int8')

In [15]:
np.__version__

'1.19.2'

In [16]:
type(arr)

numpy.ndarray

In [17]:
a = np.array((1,2,3))

In [18]:
a

array([1, 2, 3])

In [21]:
arr[0]

1

In [23]:
arr2[0,1]

2

In [25]:
arr5[0,0,0,0,4]

5

In [26]:
arr[-1]

3

In [27]:
arr2[1,1:4]

array([5, 6])

In [28]:
arr.astype('i')

array([1, 2, 3], dtype=int32)

In [29]:
arr.astype('S')

array([b'1', b'2', b'3'], dtype='|S11')

In [30]:
arr.astype(bool)

array([ True,  True,  True])

In [31]:
brr = arr.copy()

In [32]:
brr2 = arr.view()

In [34]:
brr.base

In [35]:
brr2.base

array([1, 2, 3])

In [37]:
arr2.shape

(2, 3)

In [40]:
arr2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [46]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6])

In [47]:
for x in arr:
    print(x)

1
2
3


In [48]:
for x in arr2:
    print(x)

[1 2 3]
[4 5 6]


In [50]:
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
6


In [52]:
for x in np.nditer(arr2, flags=['buffered'],op_dtypes='S'):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [54]:
for idx, x in np.ndenumerate(arr2):
    print( idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [56]:
arr.shape

(3,)

In [57]:
arr2.shape

(2, 3)

In [58]:
arr.dtype

dtype('int32')

In [59]:
arr2.dtype

dtype('int32')

In [63]:
np.concatenate((arr,brr))

array([1, 2, 3, 1, 2, 3])

In [64]:
np.concatenate((arr2,arr2),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [67]:
np.where(arr==3)

(array([2], dtype=int32),)

In [68]:
np.searchsorted(arr,2)

1

In [69]:
np.searchsorted(arr,2,side='right')

2

In [70]:
np.searchsorted(arr,[4,5])

array([3, 3], dtype=int32)

In [71]:
np.sort(arr)

array([1, 2, 3])

In [73]:
np.sort(arr, kind='selection_sort')

array([1, 2, 3])

In [75]:
np.argsort(arr)

array([0, 1, 2], dtype=int32)

In [76]:
np.argmin(arr)

0

In [77]:
np.argmax(arr)

2

In [78]:
x=[True,True,False]
newarr = arr[x]

In [79]:
newarr

array([1, 2])

In [80]:
x = arr>2
newarr = arr[x]

In [81]:
newarr

array([3])

In [82]:
from numpy import random

In [83]:
x = random.randint(100)

In [84]:
x

6

In [85]:
y=random.randint(100,size=(2,3))

In [86]:
y

array([[28, 81, 27],
       [80, 25, 75]])

In [87]:
a = random.rand()

In [88]:
a

0.4009454484557794

In [90]:
b = random.rand(6)

In [91]:
b

array([0.1311353 , 0.04461158, 0.59069394, 0.06531152, 0.88301299,
       0.04540888])

In [92]:
c = random.rand(3,4)

In [93]:
c

array([[0.4619383 , 0.27903431, 0.2105767 , 0.58445918],
       [0.86073725, 0.81006738, 0.78855357, 0.88852576],
       [0.75827474, 0.6547015 , 0.02123546, 0.44886839]])

In [94]:
d = random.rand(3,4)*100

In [95]:
d

array([[18.04318783, 40.59171028, 98.4835778 , 35.5473252 ],
       [22.2411418 , 90.68771146, 14.93120891, 25.50320752],
       [63.83091982, 95.16378729, 90.4727077 , 32.72639362]])

In [96]:
e = random.choice([3,5,7,9])

In [97]:
e

3

In [98]:
f = random.choice([3,5,7,9],size=(2,3))

In [99]:
f

array([[7, 5, 5],
       [5, 5, 5]])

In [100]:
f = random.choice([3,5,7,9],p=[0.2,0.3,0.5,0],size=100)

In [101]:
f

array([5, 3, 5, 7, 7, 5, 5, 7, 7, 3, 7, 7, 7, 7, 5, 3, 3, 7, 5, 5, 7, 3,
       7, 3, 5, 7, 7, 3, 3, 3, 3, 7, 5, 7, 5, 7, 7, 5, 7, 7, 5, 7, 5, 5,
       3, 7, 7, 5, 7, 7, 7, 7, 5, 7, 7, 5, 7, 3, 3, 7, 5, 7, 7, 7, 3, 7,
       7, 3, 7, 7, 7, 7, 7, 7, 3, 7, 3, 7, 5, 3, 5, 5, 7, 5, 7, 5, 3, 3,
       5, 5, 3, 5, 7, 7, 5, 7, 7, 5, 5, 7])

In [5]:
#np.loadtxt('file.txt')
#np.genfromtxt('file.csv',delimiter = ',')
np.savetxt('file.txt',arr,delimiter ='')
np.savetxt('file.csv',arr,delimiter=',')

In [6]:
arr.tolist()

[1, 2, 3]

In [7]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [9]:
import pandas as pd

In [11]:
data =pd.read_csv('train.csv')

In [12]:
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [13]:
data.apply(pd.Series.value_counts)

battery_power    blue  clock_speed  dual_sim     fc  four_g  \
0.0               NaN  1010.0          NaN     981.0  474.0   957.0   
0.1               NaN     NaN          NaN       NaN    NaN     NaN   
0.2               NaN     NaN          NaN       NaN    NaN     NaN   
0.3               NaN     NaN          NaN       NaN    NaN     NaN   
0.4               NaN     NaN          NaN       NaN    NaN     NaN   
...               ...     ...          ...       ...    ...     ...   
3990.0            NaN     NaN          NaN       NaN    NaN     NaN   
3991.0            NaN     NaN          NaN       NaN    NaN     NaN   
3993.0            NaN     NaN          NaN       NaN    NaN     NaN   
3996.0            NaN     NaN          NaN       NaN    NaN     NaN   
3998.0            NaN     NaN          NaN       NaN    NaN     NaN   

        int_memory  m_dep  mobile_wt  n_cores  ...  px_height  px_width  ram  \
0.0            NaN    NaN        NaN      NaN  ...        2.0       NaN  NaN   
0.1            NaN  320.0        NaN      NaN  ...        NaN       NaN  NaN   
0.2            NaN  213.0        NaN      NaN  ...        NaN       NaN  NaN   
0.3            NaN  199.0        NaN      NaN  ...        NaN       NaN  NaN   
0.4            NaN  168.0        NaN      NaN  ...        NaN       NaN  NaN   
...            ...    ...        ...      ...  ...        ...       ...  ...   
3990.0         NaN    NaN        NaN      NaN  ...        NaN       NaN  1.0   
3991.0         NaN    NaN        NaN      NaN  ...        NaN       NaN  2.0   
3993.0         NaN    NaN        NaN      NaN  ...        NaN       NaN  1.0   
3996.0         NaN    NaN        NaN      NaN  ...        NaN       NaN  1.0   
3998.0         NaN    NaN        NaN      NaN  ...        NaN       NaN  1.0   

        sc_h   sc_w  talk_time  three_g  touch_screen   wifi  price_range  
0.0      NaN  180.0        NaN    477.0         994.0  986.0        500.0  
0.1      NaN    NaN        NaN      NaN           NaN    NaN          NaN  
0.2      NaN    NaN        NaN      NaN           NaN    NaN          NaN  
0.3      NaN    NaN        NaN      NaN           NaN    NaN          NaN  
0.4      NaN    NaN        NaN      NaN           NaN    NaN          NaN  
...      ...    ...        ...      ...           ...    ...          ...  
3990.0   NaN    NaN        NaN      NaN           NaN    NaN          NaN  
3991.0   NaN    NaN        NaN      NaN           NaN    NaN          NaN  
3993.0   NaN    NaN        NaN      NaN           NaN    NaN          NaN  
3996.0   NaN    NaN        NaN      NaN           NaN    NaN          NaN  
3998.0   NaN    NaN        NaN      NaN           NaN    NaN          NaN  

[2810 rows x 21 columns]

In [14]:
data.isnull()

battery_power   blue  clock_speed  dual_sim     fc  four_g  int_memory  \
0             False  False        False     False  False   False       False   
1             False  False        False     False  False   False       False   
2             False  False        False     False  False   False       False   
3             False  False        False     False  False   False       False   
4             False  False        False     False  False   False       False   
...             ...    ...          ...       ...    ...     ...         ...   
1995          False  False        False     False  False   False       False   
1996          False  False        False     False  False   False       False   
1997          False  False        False     False  False   False       False   
1998          False  False        False     False  False   False       False   
1999          False  False        False     False  False   False       False   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width    ram   sc_h  \
0     False      False    False  ...      False     False  False  False   
1     False      False    False  ...      False     False  False  False   
2     False      False    False  ...      False     False  False  False   
3     False      False    False  ...      False     False  False  False   
4     False      False    False  ...      False     False  False  False   
...     ...        ...      ...  ...        ...       ...    ...    ...   
1995  False      False    False  ...      False     False  False  False   
1996  False      False    False  ...      False     False  False  False   
1997  False      False    False  ...      False     False  False  False   
1998  False      False    False  ...      False     False  False  False   
1999  False      False    False  ...      False     False  False  False   

       sc_w  talk_time  three_g  touch_screen   wifi  price_range  
0     False      False    False         False  False        False  
1     False      False    False         False  False        False  
2     False      False    False         False  False        False  
3     False      False    False         False  False        False  
4     False      False    False         False  False        False  
...     ...        ...      ...           ...    ...          ...  
1995  False      False    False         False  False        False  
1996  False      False    False         False  False        False  
1997  False      False    False         False  False        False  
1998  False      False    False         False  False        False  
1999  False      False    False         False  False        False  

[2000 rows x 21 columns]

In [15]:
data.notnull()

battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
0              True  True         True      True  True    True        True   
1              True  True         True      True  True    True        True   
2              True  True         True      True  True    True        True   
3              True  True         True      True  True    True        True   
4              True  True         True      True  True    True        True   
...             ...   ...          ...       ...   ...     ...         ...   
1995           True  True         True      True  True    True        True   
1996           True  True         True      True  True    True        True   
1997           True  True         True      True  True    True        True   
1998           True  True         True      True  True    True        True   
1999           True  True         True      True  True    True        True   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0      True       True     True  ...       True      True  True  True  True   
1      True       True     True  ...       True      True  True  True  True   
2      True       True     True  ...       True      True  True  True  True   
3      True       True     True  ...       True      True  True  True  True   
4      True       True     True  ...       True      True  True  True  True   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995   True       True     True  ...       True      True  True  True  True   
1996   True       True     True  ...       True      True  True  True  True   
1997   True       True     True  ...       True      True  True  True  True   
1998   True       True     True  ...       True      True  True  True  True   
1999   True       True     True  ...       True      True  True  True  True   

      talk_time  three_g  touch_screen  wifi  price_range  
0          True     True          True  True         True  
1          True     True          True  True         True  
2          True     True          True  True         True  
3          True     True          True  True         True  
4          True     True          True  True         True  
...         ...      ...           ...   ...          ...  
1995       True     True          True  True         True  
1996       True     True          True  True         True  
1997       True     True          True  True         True  
1998       True     True          True  True         True  
1999       True     True          True  True         True  

[2000 rows x 21 columns]

In [16]:
data.dropna()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [17]:
data.dropna(axis=1)

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [18]:
data.max()

battery_power    1998.0
blue                1.0
clock_speed         3.0
dual_sim            1.0
fc                 19.0
four_g              1.0
int_memory         64.0
m_dep               1.0
mobile_wt         200.0
n_cores             8.0
pc                 20.0
px_height        1960.0
px_width         1998.0
ram              3998.0
sc_h               19.0
sc_w               18.0
talk_time          20.0
three_g             1.0
touch_screen        1.0
wifi                1.0
price_range         3.0
dtype: float64

In [19]:
data.groupby('pc').mean()

battery_power      blue  clock_speed  dual_sim        fc    four_g  \
pc                                                                       
0     1257.217822  0.524752     1.471287  0.465347  0.000000  0.584158   
1     1206.173077  0.490385     1.654808  0.634615  0.000000  0.538462   
2     1214.414141  0.484848     1.600000  0.414141  0.515152  0.474747   
3     1257.602151  0.483871     1.648387  0.548387  1.064516  0.505376   
4     1143.431579  0.505263     1.532632  0.526316  1.547368  0.557895   
5     1308.389831  0.491525     1.538983  0.389831  2.338983  0.423729   
6     1276.705263  0.431579     1.487368  0.642105  2.642105  0.536842   
7     1238.941176  0.487395     1.467227  0.512605  2.974790  0.487395   
8     1179.314607  0.426966     1.379775  0.483146  3.505618  0.573034   
9     1254.794643  0.571429     1.458036  0.508929  3.544643  0.544643   
10    1203.893443  0.500000     1.477049  0.516393  4.278689  0.483607   
11    1233.683544  0.594937     1.545570  0.506329  4.822785  0.506329   
12    1213.400000  0.511111     1.445556  0.500000  5.366667  0.522222   
13    1264.270588  0.517647     1.583529  0.611765  5.364706  0.564706   
14    1201.865385  0.528846     1.472115  0.442308  6.615385  0.519231   
15    1172.532609  0.532609     1.431522  0.456522  6.663043  0.500000   
16    1320.318182  0.420455     1.504545  0.511364  7.250000  0.454545   
17    1215.252525  0.454545     1.545455  0.484848  7.676768  0.575758   
18    1355.792683  0.512195     1.641463  0.463415  8.134146  0.597561   
19    1315.951807  0.518072     1.489157  0.542169  8.084337  0.518072   
20    1242.045455  0.418182     1.620909  0.500000  9.009091  0.472727   

    int_memory     m_dep   mobile_wt   n_cores   px_height     px_width  \
pc                                                                        
0    31.336634  0.476238  136.950495  4.564356  691.188119  1236.594059   
1    32.307692  0.471154  137.673077  4.605769  577.028846  1251.971154   
2    31.787879  0.563636  138.060606  4.929293  669.212121  1268.919192   
3    33.182796  0.466667  140.451613  4.494624  585.301075  1228.010753   
4    34.326316  0.474737  144.789474  4.294737  675.263158  1206.378947   
5    33.084746  0.479661  144.983051  4.254237  694.322034  1179.474576   
6    32.757895  0.525263  140.810526  4.747368  684.852632  1286.610526   
7    31.563025  0.467227  139.319328  4.436975  698.310924  1285.924370   
8    33.325843  0.501124  137.775281  4.752809  709.629213  1304.876404   
9    30.991071  0.495536  135.830357  4.401786  702.500000  1313.000000   
10   33.516393  0.511475  139.524590  4.336066  602.516393  1229.844262   
11   33.683544  0.512658  139.291139  4.278481  618.088608  1220.202532   
12   35.133333  0.507778  146.944444  4.477778  571.722222  1222.622222   
13   31.482353  0.524706  143.400000  4.188235  586.964706  1195.023529   
14   30.817308  0.510577  141.230769  4.509615  601.653846  1211.778846   
15   30.750000  0.547826  137.804348  4.663043  704.673913  1307.086957   
16   29.181818  0.451136  144.750000  4.136364  633.920455  1272.056818   
17   32.161616  0.528283  135.090909  4.717172  575.939394  1234.757576   
18   31.621951  0.495122  141.036585  4.658537  694.231707  1318.792683   
19   29.831325  0.538554  141.831325  4.686747  680.746988  1277.867470   
20   30.672727  0.492727  142.027273  4.681818  611.645455  1206.827273   

            ram       sc_h      sc_w  talk_time   three_g  touch_screen  \
pc                                                                        
0   1916.980198  11.801980  5.831683  10.267327  0.821782      0.504950   
1   2054.125000  12.317308  5.451923  11.740385  0.759615      0.509615   
2   2194.343434  12.050505  5.787879  10.505051  0.777778      0.515152   
3   2107.731183  12.000000  5.494624  10.548387  0.752688      0.494624   
4   2040.463158  13.389474  6.421053  10.989474  0.757895      0.389474   
5   2225.254237  13.033898  6.423729  11.915254  0

In [25]:
data.pivot_table(index = 'blue',values = ['fc','pc'])

fc        pc
blue                    
0     4.294059  9.976238
1     4.325253  9.855556