In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4],np.int32)

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [5]:
a[3]

4

In [6]:
a.shape

(4,)

In [7]:
a.dtype

dtype('int32')

In [9]:
a[0]=90

In [10]:
a

array([90,  2,  3,  4])

In [11]:
l = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
l.size

9

In [14]:
zeroes = np.zeros([5,1])

In [15]:
zeroes

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [16]:
zeroes.dtype

dtype('float64')

In [17]:
rng = np.arange(6)

In [18]:
rng

array([0, 1, 2, 3, 4, 5])

In [21]:
lspace = np.linspace(1,5,4)

In [22]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511562e-306, 1.89146896e-307, 1.37961302e-306],
       [6.23053614e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 9.34603000e-307],
       [1.78018403e-306, 8.90106955e-307, 1.60218491e-306,
        1.78018403e-306, 1.69119330e-306, 6.23054633e-307],
       [1.60219578e-306, 7.56601165e-307, 6.23061763e-307,
        2.22523140e-306, 6.89806849e-307, 2.46155235e-312]])